### ISSUE TITLE
DGL training error

### ISSUE THREAD

**Issue by Yash685** [xxcclong/history-cache#1]
When using train.type as "dgl" and load as "cxg", the function 'self.cxg_dgl_train_epoch()' is called . But the execution of it fails by throwing out error saying 'self.table.sub_to_history_layered' is not found inside prepare_history_x function. The self.table points to object of HistoryCache but there is no declaration of variable name 'sub_to_history_layered'

**Comment by xxcclong** [comment]
Hi, 
It is fixed in https://github.com/xxcclong/history-cache/commit/f19054c3666ba66e7820fa4cf149b2fa4eda49f3
However, historical cache has more stable support for CxG models than DGL models, we recommend to use CxG models.

**Comment by Yash685** [comment]
To run historical cache in dgl , we need self.type (train.type) as "dgl" and self.load_type (dl.type) as "cxg" which is as per mentioned in [history_trainer.py](https://github.com/xxcclong/history-cache/blob/master/hiscache/history_trainer.py#L232). This gives error as
```
Error executing job with overrides: ['dl/dataset=arxiv', 'dl.type=cxg', 'train.type=dgl', 'dl.loading.feat_mode=history_uvm', 'dl.sampler.train.batch_size=8192', 'train.train.num_epochs=2', 'dl.num_device=1', 'history.limit=10', 'history.rate=0.9']
Traceback (most recent call last):
  File "/media/yash/HEC/history-cache/example/main.py", line 29, in main
    trainer.train()
  File "/home/yash/miniconda3/envs/hiscache/lib/python3.11/site-packages/History_Cache-0.0.1-py3.11-linux-x86_64.egg/hiscache/history_trainer.py", line 314, in train
    self.cxg_dgl_train_epoch()
  File "/home/yash/miniconda3/envs/hiscache/lib/python3.11/site-packages/History_Cache-0.0.1-py3.11-linux-x86_64.egg/hiscache/history_trainer.py", line 109, in cxg_dgl_train_epoch
    batch_pred = self.model([blocks, batch_inputs])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/yash/miniconda3/envs/hiscache/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/yash/miniconda3/envs/hiscache/lib/python3.11/site-packages/History_Cache-0.0.1-py3.11-linux-x86_64.egg/hiscache/history_model.py", line 121, in forward
    x = batch.x
        ^^^^^^^
AttributeError: 'list' object has no attribute 'x' 
```
Also loader is dependent on cxgnn.get_loader(config.dl) which inside takes value of dl.type, passes through dictionary and returns corresponding CXGLoader or DGLLoader, but in our case it will return CXGLoader because dl.type should be "cxg" as mentioned above and we can not pass both arguments as dgl since dataloading is custom which needs cxg. Thus I am facing issue in running it with dgl

**Comment by xxcclong** [comment]
We will take a look at it.

**Comment by xxcclong** [comment]
Hi, this is because the historical convolutions, e.g. `HistorySAGE`, uses new kernels from `hiscache_backend`, so full training with history are only supported when using train_type=cxg (as there are no historical GPU kernels in DGL). Could you further explain why you want to use DGL for historical training instead of CXG? We can see if there are some workarounds.

**Comment by UtkrishtP** [comment]
Thanks for reverting back.
Since we are using DGL exclusively in our experiments, we were looking whether the DGL kernels have been modified to support hiscache.

**Comment by Yash685** [comment]
Thanks for reverting. In the code in order to run with dgl you have mentioned to pass `self.train.type="dgl"` and `self.load.type="cxg"` which in turn calls cxg_dgl_train_epoch(). In that function before doing forward pass you have called `blocks = self.to_dgl_block(batch)` and after that when forward pass is called `batch_pred = self.model([blocks, batch_inputs])` which in turn calls HistorySAGE forward() function. Now this forward() is not supported to take input [blocks,batch_inputs], all the calls and data extraction is based on 'batch' variable (given by CXGLoader).
Is there any way to support DGL blocks in cxg training pipeline?

**Comment by xxcclong** [comment]
Some modifications to the DGL CUDA kernels might be needed to use history cache, otherwise it may lead to wrong results.
